[package]
name = "bitonic_sort_portable_simd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
criterion = "0.4.0"
rand = "0.8.4"

[[bench]]
name = "benchmarks"
harness = false